// Regenerates seed/seed.sql from the markdown files in seed/posts/.
// Usage: npm run build:seed

import { readdir, readFile, writeFile } from "node:fs/promises";

const POSTS_DIR = new URL("./posts/", import.meta.url);
const OUT_FILE = new URL("./seed.sql", import.meta.url);

function parseFrontmatter(raw) {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) throw new Error("Missing frontmatter block");
  const [, fm, body] = match;
  const data = {};
  for (const line of fm.split(/\r?\n/)) {
    if (!line.trim()) continue;
    const idx = line.indexOf(":");
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
    data[key] = value;
  }
  return { ...data, content: body.trim() };
}

function sqlString(value) {
  if (value === undefined || value === null || value === "") return "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

const files = (await readdir(POSTS_DIR)).filter((f) => f.endsWith(".md")).sort();

let sql = "-- Generated by seed/build-seed.mjs — do not edit by hand.\n\n";
for (const file of files) {
  const raw = await readFile(new URL(file, POSTS_DIR), "utf8");
  const post = parseFrontmatter(raw);
  const timestamp = new Date(`${post.date}T12:00:00Z`).toISOString();
  const published = post.published === "false" ? 0 : 1;
  const section = post.section || "blog";

  sql += `INSERT INTO posts (slug, title, excerpt, content, cover_image, cover_focus, source_note, published, section, created_at, updated_at)\n`;
  sql += `VALUES (${sqlString(post.slug)}, ${sqlString(post.title)}, ${sqlString(post.excerpt)}, ${sqlString(post.content)}, ${sqlString(post.cover_image)}, ${sqlString(post.cover_focus)}, ${sqlString(post.source_note)}, ${published}, ${sqlString(section)}, ${sqlString(timestamp)}, ${sqlString(timestamp)});\n\n`;
}

await writeFile(OUT_FILE, sql, "utf8");
console.log(`Wrote ${files.length} posts to seed/seed.sql`);
