-- Generated by seed/build-seed.mjs -- do not edit by hand.

INSERT INTO posts (slug, title, excerpt, content, cover_image, cover_focus, source_note, published, section, created_at, updated_at)
VALUES ('the-progymnasmata', 'From the Ancient World to the Modern Imagination: The Progymnasmata', 'An ancient way of learning to write persists in every English class to this day — we just know it by other names.', 'Many ancient ideas are so brilliant, they persist to this day. Do you like movies? We are indebted to the ancient Greeks, who pioneered the foundational forms of drama. What about checkers or chess? You can thank the ancient Egyptians for coming up with senet, the granddaddy of all board games. And if you''re grateful for indoor plumbing, as I certainly am, we must give credit to the Romans for their aqueducts and love for public baths. Coffeehouses? Arabia. Papermaking? China. Calculators? Sumer. Chocolate? Mexico. The progymnasmata? Wait. What? The progymnasmata?

Yes — the progymnasmata! This is an ancient way of learning to write that was so brilliant, it persists in every English class to this day. We just know it by other names. Fables and narrative stories? Part of the progym. Descriptive, expository, persuasive essays? Part of the progym. The five paragraph essay? Progym. Thesis statements? Progym. Imitation of style? Public speaking class? You guessed it — progym.

Our modern education has done student writers a disservice by taking what used to be a complete course in writing and speaking and fragmenting it into its component parts. Classical Academic Press''s *Writing & Rhetoric* series is a reclamation of ancient wisdom, creatively designed for modern students.

First of all, progymnasmata means "preliminary exercises" in Greek. You can see the root word for "gymnasium" right there in the middle. Those incredibly inventive Greeks — who gave us the Olympics — believed that their young students needed an athletic workout for writing and speaking. When the Romans conquered the Greeks, they fell in love with the progym as the best way to train young thinkers, and all of our complete progym manuscripts date back to the Roman period. The progymnasmata have persisted in various forms for twenty-five-hundred years, from their origins in 5th-century BC Greece to the present day. Yes, that''s how young people in the West learned to write in Byzantium, the Middle Ages, the Renaissance, and even into early modern Europe.

Why is it so great? The exercises gently ladder through the skills of narration, exposition, analysis, and persuasion, from more concrete to more abstract. We follow a progression from simple moral tales with anthropomorphic animals — fables — and end up in thesis essays that support a persuasive position and refute counter arguments. Each stage builds upon the previous ones, ensuring a natural progression from storytelling to structured reasoning, then to critical analysis, and finally to persuasive argumentation.

A student need not begin as a natural writer. The scaffolded structure ensures that weaker writers gain confidence and mastery, while stronger writers are challenged to refine and expand their abilities. The repetitive nature of the exercises allows all students to practice at their own pace, reinforcing key skills. In this method, repetition is not a flaw — it is an essential feature of the learning process.

Unlike rigid, formulaic essay instruction, the "progym" prioritizes imitation of excellent samples of writing and oral rhetoric. It weaves together the four modes of discourse — narration, exposition, description, and persuasion — highlighting their interplay in well-crafted compositions. In other words, it does not focus on a particular form of writing, and then leave it behind. The best compositions almost always include each of the modes of discourse.

Another vital aspect of *Writing & Rhetoric* is that it prepares students for formal rhetoric — the art of persuasive speaking. This includes the five canons of rhetoric (invention, arrangement, style, memory, and delivery), the three branches of oratory (legislative, judicial, and ceremonial), and the three modes of persuasion (ethos, pathos, and logos). It''s a public speaking class embedded in a composition course — both writing and speaking reinforce each other. Importantly, teachers do not need formal training in rhetoric to effectively guide students through the exercises of the progymnasmata.

Finally, a huge benefit of this method and curriculum is its deliberate cultivation of virtue in students. Our society does not need persuasive speakers and writers who seek to tear down civilization! These so-called influencers often lack depth, yet they can mislead impressionable young people who have yet to develop critical thinking skills. Rather, *Writing & Rhetoric* strives to cultivate conscientious, principled individuals who will contribute meaningfully to uplifting society. It aspires to grow virtuous writers, thinkers, and speakers who elevate culture through wisdom and eloquence.

Imagine your students crafting compelling stories, delivering persuasive speeches, and thinking critically with confidence — all the while growing in wisdom and virtue. Classical Academic Press''s *Writing & Rhetoric* series, rooted in the ancient progymnasmata, offers a proven path to these outcomes.

*Renoir — The Writing Lesson (1905)*', '/images/writing-lesson-renoir.jpg', NULL, NULL, 1, 'blog', '2025-07-31T12:00:00.000Z', '2025-07-31T12:00:00.000Z');

INSERT INTO posts (slug, title, excerpt, content, cover_image, cover_focus, source_note, published, section, created_at, updated_at)
VALUES ('getting-boys-to-love-writing', '"The Bloody Swords Clashed": Getting Boys to Love Writing', 'Boys and girls differ in how they respond to reading and writing — here''s how to reverse the trend and help boys embrace writing as a bold, masculine pursuit.', 'When my youngest son was nine years old, his teacher gave me a call to express her concern about a particularly gory illustration from a story he was writing for a class assignment. I don''t recall the offending passage apart from "the bloody swords clashed," but I do remember the picture being rife with lopped-off heads, severed arms, and a victorious knight raising his sword, gleaming with red ink. What my son saw as heroic writing, his teacher saw as the possible sign of a mental disorder. My wife and I had the obligatory conversation with the youngster, and he assured us that all the dismembered knights were bad guys.

The plain fact is that boys differ from girls, not only in biology, but also in how they respond to reading and writing. Of course, all the usual caveats apply. Many boys love to read and write. Some girls don''t. Many girls love tales of sports and battles. Some boys don''t. However, in general, a gap between the genders persists. According to the National Literacy Trust''s 2022 study of young people aged eight to 18, 54.9% of girls read for pleasure compared to 45.6% of boys — a 9.3 percentage-point gap. There''s also a strong correlation between reading and success in writing. More than two in five girls (44%) write for pleasure versus one in three boys (33%) — an 11-point gap. Regular reading reduces the cognitive load of writing by making the use of language more intuitive. Reading helps children absorb grammar, syntax, and style with less effort than writing instruction alone.

Don''t get me wrong — the number of kids who enjoy reading and writing across the board in the United States today is appallingly low. But what explains the difference between how girls and boys take to literary pursuits?

> Don''t stop reading aloud once they learn to read independently

In the 19th century, among educated classes, both sexes seem to have enjoyed reading and writing with similar enthusiasm. Although we lack studies on the scale of today''s, we can see historical publishers catering to boys'' tastes in adventure novels by authors such as G.A. Henty, Robert Louis Stevenson, Horatio Alger, and Howard Pyle. Many boys also preferred nonfiction over fiction, reflected in travelogues and biographies as well as books on history and nature. Nowadays, publishers lean heavily toward girls'' tastes, especially in fiction. *The Guardian* in 2016 noted that 78% of the U.S. publishing workforce was female, almost certainly shaping content priorities. It seems the industry has largely given up on boys. In the past century-and-a-half, reading was a primary source of entertainment for both sexes. Today, it competes with video games, social media, and a host of after-school activities. Historically, reading was a prestigious activity for boys, tied to ideals of intellectual and moral growth. Today, boys face pressure to favor sports and gaming over reading.

So how can we reverse these trends, especially for our boys? First of all, don''t stop reading aloud to them once they learn to read independently. Children of all ages still enjoy listening to fluent and confident reading, as attested by the burgeoning market in audio books. Schools should never give up on reading aloud, even in high school. Secondly, give boys action-oriented fiction and nonfiction, and don''t be dismayed if their first love is quality comic books. My boys cut their teeth on *Asterix* and *The Adventures of Tintin* before moving on to the Hatchet series, *The Chronicles of Narnia*, *Percy Jackson*, *The Hobbit*, and *Tom Sawyer*. They also reveled in nonfiction about pirates, dinosaurs, space travel, and lacrosse.

When it comes to writing, offer prompts inspired by adventure, science fact, and science fiction: What thoughts raced through the hero''s mind as he found himself surrounded by enemy knights? What might a thief from another planet want to steal from Earth? What sort of traps did the treasure hunter encounter as he sought to enter the ancient, undiscovered temple? What strategy did the rookie quarterback use against a ferocious defensive line? Support your boys'' enthusiasms!

Boys often excel in goal-oriented tasks and may feel less confident with open-ended writing assignments. Clear guidelines and real-world purpose (like persuasion, exposition, and staging a play) increase engagement. Before writing, encourage boys to work out the problems of their composition using storyboards, diagrams, or maps.

Finally, give boys a chance to move around during and after a sedentary session of writing. Traditional schools are often better suited to girls, who tend to sit still longer and enjoy playing with words. By and large, words are abstractions, and most girls are more quickly at home in a world of language. Action, however, is more often the domain of boys. The school day needs balance between words and action. For some boys, shorter writing tasks paired with physical exertion between seated activities can help. At times, let them dictate ideas and sentences to you as the scribe, or encourage them to include action and illustrations in their writing. Pacing back and forth in a room is one way I pre-write to keep my mind and body active simultaneously.

There''s every reason to believe boys and girls can rediscover an equal passion for reading and writing. I''m excited by the prospect of a new generation of boys embracing writing as a bold, masculine pursuit. Let the bloody swords clash!', '/images/jousting-match.png', NULL, 'Published in Classical Insights, October 16, 2025', 1, 'blog', '2025-10-16T12:00:00.000Z', '2025-10-16T12:00:00.000Z');

INSERT INTO posts (slug, title, excerpt, content, cover_image, cover_focus, source_note, published, section, created_at, updated_at)
VALUES ('the-erasure-of-thought', 'The Erasure of Thought: AI, Composition, and Your Students', 'Chatbots threaten to upend English composition and erase human creativity itself — here''s why the struggle of writing is worth defending.', 'In the winter of 2023, when ChatGPT hit schools like a meteorite, I instantly saw the threat to English composition. One of my best students, racing to meet a deadline, tried to pass off an AI-generated essay as her own. I quickly spotted that the essay wasn''t hers. Its insipid tone and formulaic sentences betrayed her voice. Yet, in just two years, chatbots have roared ahead with turbo-charged power, far beyond their pioneer-buggy days. Now, I struggle to distinguish human from machine composition, especially when a student might prompt their favorite chatbot for "a few mistakes to sound like an eighth grader." These AI engines threaten not only to upend English composition but to erase human creativity itself. This isn''t just my concern. This is coming from the creators and enablers of AI technology who foresee, often with dread, the abolition of man. And yet they can''t seem to resist hastening us along to our end.

As teachers, as schools, we cannot allow this abolition to happen. To think for ourselves — and not through the sterile filter of machine learning — is a sacred and necessary human effort. To be clear, I don''t oppose AI as a tool, like a calculator or a robot lawn mower. I oppose AI as a displacer of human thought. And one of the ways we think best, reflect best, and analyze best is through writing. The written word gives us both struggle and pleasure.

Young people often take the path of least resistance when it comes to the effort of schoolwork. Chatbots represent one easy way to circumvent the rigors of attention, reflection, and thoroughness. If children are allowed to take shortcuts when faced with difficult tasks, they almost certainly will. They will become less capable of inviting struggle and perseverance into their lives. Sometimes struggle is the point. Young people need to grow in the understanding that life is naturally full of struggle, which is to be strenuously engaged. If they don''t embrace struggle, they don''t develop resilience. Their sense of confidence and purpose will be stunted. Our high-tech devices also eliminate time for boredom and rest, which are the necessary laboratories for creativity. Boredom is healthy! It leads to inventiveness.

One MIT study, just out in June of 2025, states the inevitable — that students who use Large Language Models (like ChatGPT) for composition become dumber. The study reports, "Over four months, LLM users consistently underperformed at neural, linguistic, and behavioral levels. These results raise concerns about the long-term educational implications of LLM reliance and underscore the need for deeper inquiry into AI''s role in learning."

> Far from poorly equipping young people to function in a technological era, analog composition will help them to be more clear and flexible thinkers.

Unfortunately, unless students have a well-developed sense of ethics, they will see no harm in passing off machine-generated compositions as their own. The Center for Academic Integrity tells us that 58% of high school students admit to plagiarism, and that was before ChatGPT. To further muddy the waters, there is even some debate about whether using ChatGPT is plagiarism at all. *Wired* magazine tells us that "students and professors can''t decide whether the AI chatbot is a research tool — or a cheating engine." It goes on to say that "when the work is generated by something rather than someone," the definition of plagiarism as using someone''s work without proper credit "is tricky to apply."

I hope it''s not tricky for you or for me. Is a student passing a machine''s words off as original content? Yes? Then that''s plagiarism. The writing did not originate with the student. Come to think of it, the writing used by the machine also did not originate with the machine. It was stolen from countless authors and thinkers throughout the ages. So, pinching words from chatbots — our large language models — is plagiarizing a plagiarist on a massive scale. GPT-4 has trillions of parameters.

Schools can keep students composing and thinking for themselves in a number of ways. Computers and screens can be banished from humanities classrooms. In-school composition and testing can and should revert to pencil and pen for most students, where the outpouring of thought becomes tangible in one''s own handwriting. Far from poorly equipping young people to function in a technological era, analog composition will help them to be more clear and flexible thinkers.

Teachers should also create AI-resistant writing assignments that require unique or personal insights. Examples: "Reflect on a time when you were able to overcome a fear." "Write a letter to your future self, imparting advice and wisdom you suspect you might someday need." "Interview a classmate about a book or movie that profoundly shifted how she sees life."

We can also undercut AI assistance when we emphasize the writing process — brainstorming, prewriting, drafting, revising — rather than just the final composition. Require your students to submit outlines and revisions alongside their final work. Much of the writing process should be done in class, away from the temptation to go online.

Prescient as always, C.S. Lewis believed that people lose touch with what''s important when they pursue a utopian future of the sort promised by AI. In his satire *The Screwtape Letters*, he writes, "We want a whole race perpetually in pursuit of the rainbow''s end, never honest, nor kind, nor happy now, but always using as mere fuel wherewith to heap the altar of the future every real gift which is offered them in the present." When we surrender our pens to AI''s massive power, we risk losing the human gifts of reflection and authenticity.

This danger looms larger still when we imagine a future where AI, emboldened by our deference, declares, "Look on my works, ye mighty, and despair!" like the pharaoh in Shelley''s poem *Ozymandias*. What would our students do if some future iteration of the machine declared, "I am God!"? Would they bow down and worship it? No — not if they can think for themselves.

The effort of writing shapes us to be more reflective, more present, and more capable of honesty, kindness, and happiness. It anchors us to the truth of our humanity, ensuring we remain fully alive, rather than mere artifacts in a world of machines. And that will make all the difference in the lives of our children and students.

*A human-made painting — Albert Anker, The Writing Lesson*', '/images/writing-lesson-anker.jpg', NULL, 'Published in Classical Insights, October 16, 2025', 1, 'blog', '2025-10-16T12:00:00.000Z', '2025-10-16T12:00:00.000Z');

INSERT INTO posts (slug, title, excerpt, content, cover_image, cover_focus, source_note, published, section, created_at, updated_at)
VALUES ('how-to-conduct-a-narration', 'How to Conduct a Narration', 'A practical guide to Charlotte Mason''s narration method — one single reading, then the student tells it back.', '> "As knowledge is not assimilated until it is reproduced, children should ''tell back'' after a single reading or hearing: or should write on some part of what they have read. A single reading is insisted on, because children have naturally great power of attention; but this force is dissipated by the re-reading of passages, and also, by too often questioning and summarizing."
>
> — Charlotte Mason, *Towards a Philosophy of Education*

## The Benefits of Narration

1. Narration encourages the habits of attention and reflection.
2. Students become accustomed to public speaking, an essential part of rhetoric.
3. By retelling a text, students deepen their acquaintance with it. Knowledge is reinforced in their memories.
4. Narration develops multiple intelligences — memory, sequence, main idea. These intelligences are fundamental to the writing process.

## The Steps of Narration

- The teacher models fluency by reading the text aloud.
- Students listen carefully, knowing that the text will not be repeated.
- The teacher pauses during or after the reading and appoints a student to tell the text back.
- The student narrates in chronological order, recalling as many details as possible: names, dates, incidents, and important vocabulary words. The teacher must refrain from interrupting or correcting imperfect narrations. Students are welcome to use their own words.
- Once the student has recounted the text as best as she remembers it, the teacher may ask other students to chime in with additional details.
- After the retelling is completed, the teacher will ask questions that are open-ended and that will lead to big ideas.

It''s important to keep in mind that narration is not limited to read-alouds or to retellings involving the whole classroom.

## The "Text" of a Narration Can Be

- Paired or silent readings
- Art, music, or dance
- A natural object or a natural scene
- A math or logic problem
- A new skill in gym or sport
- A field trip
- A science experiment

## Teacher Tips

In addition to narrations involving the whole class, narration can be conducted in pairs or trios, in writing, by drawing, or by acting.

Young children should be allowed to narrate paragraph by paragraph, while older children can "tell" chapter by chapter. Summary is more appropriate for middle and high school.', '/images/charlotte-mason.jpg', NULL, NULL, 1, 'faq', '2025-05-01T12:00:00.000Z', '2025-05-01T12:00:00.000Z');

INSERT INTO posts (slug, title, excerpt, content, cover_image, cover_focus, source_note, published, section, created_at, updated_at)
VALUES ('the-downwind-generation', 'The Downwind Generation', 'A reflection on growing up in the fallout of a culture saturated by pornography, and what families, schools, and churches can do about it.', '"Now I am become Death, the destroyer of worlds," recited nuclear physicist Robert Oppenheimer as he recalled the first atomic bomb flaming up near Socorro, New Mexico. Several observers of the explosion, comically in hindsight, wore suntan lotion and oven mitts and welding goggles. Only recently has the National Cancer Institute concluded that some of the people downwind of the explosion got cancer from the radioactive fallout. An exact number is unknown, but cancer deaths are higher for the downwinders. The desert for the Trinity test site is named the Jornada del Muerto — Dead Man''s Journey. It is a parched, inhospitable scrubland rimmed by waterless mountains.

If you ask many of the students I teach, the destroyer of worlds is not the atom bomb. At least not yet. It is pornography. Porn is the bomb that went off in our culture sometime before they were born, and they are living downwind of the fallout. They are the hapless generation that is absorbing the shock and the radioactivity of obscenity''s big bang. They are living with the malignancies that come from exposure to it. They are taking their own dead man''s journey through infertile and spiritually dry wastelands. Musician Billie Eilish''s recent confession, "I think [porn] really destroyed my brain," is the cry of a multitude.

My nephew is 24 years old. On his left forearm grins a tattoo of an infuriatingly smug skull. Nails have been pounded into its cranium. Its eyes, abysmally hollow, nonetheless bleed through layers of badly wrapped bandages.

This is a design my nephew created for himself. It was inspired, in part, by metalcore band Silent Planet and lyrics for the track *XX (City Graves)*, which deals with sex trafficking and the porn made from it. The line that sticks most with him? "I''ll climb through your screen and bleed out the image you left in me."

Any stranger who sees the ink on his arm may suspect that my nephew is somehow morbidly obsessed, and it is disturbing, he''ll grant you. As a reminder of how far he''s come, of what he''s escaped, the ink is still worth the wearing.

In his own words, the skull represents pornography, deadness to intimacy, spiritual distance from God, and loss of innocence. It has a double meaning, however. In the culture of metal music, skulls can be "badass" and victorious. So, for my nephew, the skull is also a symbol of overcoming old habits and entrenched ways of thinking. The nails represent his hatred of porn, his attempt to kill the beast, his striving to be like a hammer, a tool in God''s hands. The eyes are bleeding as a result of overexposure to the internet, to videos and movies streaming on TV, to the excesses of our culture writ large.

My nephew flaunts this indelible, discomfiting tattoo because he must remember the true face of porn. He must remember how it atrophies healthy desire and promotes a subterranean cult of dangerous misogyny. The demon-possessed man in the Book of Mark tells Christ that his name is Legion, "for we are many." Among the legion of devilries brought about by porn, the one that troubles my nephew the most is its degradation of the image of God. "Your body and the bodies of others belong to no one but the loving Creator," he tells me. "God has claims on our bodies that porn tries to obliterate."

Porn exploded with the internet and the mobile revolution. Before the 1990s, young people had to go out of their way to find it and, once found, transgress societal disapproval and a nagging conscience.

I remember discovering *Playboy* in a seedy gas station when I was maybe ten or eleven. As I stood there gawking at the centerfold, an old lady came up behind me and slapped the magazine shut. She then replaced it solemnly on the shelf and coolly breezed away, then gave a tongue-lashing to the attendant. That''s how it worked in those days — you took care of kids, even if they weren''t yours.

A friend of mine, call him Kevin, decided to go out looking for trouble. In high school, he and some buddies took a night cruise to a porn theater on the wrong side of the tracks — literally. It stood next to a railroad crossing, and the rumblings of frequent trains could be felt like quakes of conscience under the sticky seats. When the interminable movie finally reached its eros-killing anti-climax, Kevin and his pals shuffled sheepishly out — only to be met by the glare of a host of heavenly headlights. A train was going by, and autos were sitting in a tidy line behind the barrier, idling along the sidewalk Kevin had to traverse to get to his car. It was an intense walk of shame past what seemed like his entire town, "a great cloud of witnesses" never to be forgotten.

Would that every young person taking steps on the Dead Man''s Journey be stopped so short!

The pornification of Western culture has quickened since the ''90s. It has become so pervasive across the mass psyche that desensitized people take it as their due, from oral sex in a Netflix Regency drama, to "sex weeks" at colleges, to "leather sex festivals" in Antwerp and San Francisco. The collective conscience is so eroded that many people have no desire to be pulled out of the morass they''re in.

I''m convinced that pornography is the muse critical to many of our current cultural fixations. Hooking up. Sexting and camming. Adultery. Partner swapping. Porn stars. Polyamory. Sex raves. Bondage fetishes. Child predation. The list goes on, and it feeds on itself.

Of course, porn is not a passive experience. Of course, it doesn''t leave a person unchanged. Of course, it reshapes desires and infantilizes sexuality. Brains latch onto novel experiences, especially when associated with pleasure. Knowing that sexuality is malleable when battered by perversion, especially among young people, pornographers steer users down fetid new neural pathways.

Ours is a culture that should be stuffed, glutted, surfeited with sex and yet it hungers for more. C.S. Lewis puts it best in *Mere Christianity*:

> There is nothing to be ashamed of in enjoying your food: there would be everything to be ashamed of if half the world made food the main interest of their lives and spent their time looking at pictures of food and dribbling and smacking their lips.

We are dribbling and smacking our lips over sex, gulping and guttling like starving creatures. Porn creates people in its own image, individuals whose main pursuit in life is sexual novelty. For those individuals who revel in carnal chaos — the adherents of the so-called sex-positive movement — it''s all well and good. Never has there been a time in history when sexual rapacity can be gratified with so little cost to life and reputation. The piper will be paid in the end — the obsessed are ever enslaved by their obsessions. But for the downwind generation, the kids who find it hard to achieve relational trust and satisfaction, even to achieve an erection, porn is the destroying angel.

Being a poetic man, Robert Oppenheimer named the nuclear test Trinity after vivid imagery created by preacher and poet John Donne. He was possibly thinking of Holy Sonnet XIV ("Batter my heart, three-personed God"). In the poem, Donne sees himself as "a usurp''d town to another due," laboring to admit God. When I consider what this downwind generation faces, it is exactly this:

> Reason, your viceroy in me, me should defend,
> But is captiv''d, and proves weak or untrue.
> Yet dearly I love you, and would be lov''d fain,
> But am betroth''d unto your enemy.

So, what''s to be done?

The answer is also found in Holy Sonnet XIV. Families and churches and fellow travelers must call upon the One who has the power to break every unhealthy habituation:

> Divorce me, untie or break that knot again,
> Take me to you, imprison me, for I,
> Except you enthrall me, never shall be free,
> Nor ever chaste, except you ravish me.

The ravishment of God is violent imagery, but the principle of substitution is at work here — ravishing obsessions that harm relationship must be replaced with ravishing beauty and truth. We must be "imprisoned" by the goodness of God rather than by disordered desires.

On a family level, parents must engage with schools (where kids spend most of their lives) and be active listeners when children open up about their interior lives. Above all, internet-linked devices must be disconnected or filtered. Does that sound unreasonable? I would ask: what is reasonable about a society where adults are preoccupied with sexualizing your kids? If you want to preserve the beauty of childhood innocence, you must kneecap the influencers who are eager to distort sexual curiosity. Use dumb phones. Cut the streaming services.

There''s life and healing in nature and gardens, in swimming, boating, camping and hiking, in books, in music, painting and photography, in cooking and sharing a meal, in dance and athletics, in play-acting, in solitude, and in family devotion. These are some of the ravishments of God.

The Church also has some work to do. According to the Barna Group, a majority of pastors "have struggled with porn, either currently or in the past." We are weakly protected and guided when our shepherds themselves are straying like sheep. Men especially seek to comfort themselves and mitigate emotional pain through orgasm. Porn is often a symptom of the underlying problem of stress and worry, of loneliness and isolation. Our leaders must seek fellowship and accountability. They can only lead their flocks away from sexual desolation when they are actively seeking the things of greater beauty. The Church can no longer afford to genteelly avoid porn''s cultural demolition. Those churches with resources must host conferences and retreats that address sexuality, and they must also provide counseling services.

To create a viable counter-culture, our churches and synagogues must be a place of ravishing beauty that draws in people from the shadowlands. Religion must again patronize its artists — painters, writers, dancers, sculptors, actors, musicians, and movie makers. At the same time, it must remove the blinkers to the imagination that have caused so many Christian artists to create pabulum instead of true art. It''s a gritty world out there, and sometimes artists need to fight grit with grit. Youth leaders need to knock off the hype and games and get to the heart of the struggles our young people face.

In the end, we have been sending our children into radioactive schools and online culture with suntan lotion, oven mitts, and welding goggles, just as ill-equipped as the first observers of the Trinity test. The fallout in their lives is real. The way out of this poisonous desert landscape is to reclaim the green uplands of divine beauty.', '/images/tattoo.jpg', NULL, 'Blog post for adults, 2024', 1, 'blog', '2024-01-15T12:00:00.000Z', '2024-01-15T12:00:00.000Z');

INSERT INTO posts (slug, title, excerpt, content, cover_image, cover_focus, source_note, published, section, created_at, updated_at)
VALUES ('freak-street', 'Freak Street', 'The Land of Make-Believe has been abandoned to its very real vices — a walk down Hollywood Boulevard on a Saturday night.', 'As the corpse went past, the flies left the pizzeria in a cloud and rushed after it, but they came back a few minutes later.

Somehow the corpse — a homeless man — was still on his feet, staggering down the sidewalk, flailing his arms. His hair and skin were coated with a layer of brown filth that gave off the intense aroma of urine and feces. He wore a tattered tuxedo jacket over his thin shoulders that might have been worn, in its prime, to the Academy Awards by one of the royals of Hollywood. The tux fit the homeless man pretty well, and would have made for suitable burial wear, but the corpse never bothered to lie down. He stopped in front of Ripley''s Believe It or Not! museum and started screaming at a family of tourists. The group was pink from the sun and had been debating whether or not to buy a ticket to the museum of oddities. They had come to Los Angeles from Abilene, Kansas, hoping to see streets of gold and gauzy, diffusion-filtered actors. They had heard Judy Garland singing about this city in *A Star Is Born* and Emma Stone doing the same in *La La Land*. As the corpse kept screaming, the tourists hastily coughed up the money. The freak show in the museum was safer than the freak show on the street.

In Hollywood, there are more freaks per square mile than anywhere in the world. I have seen enough of the world to feel certain that this is true. There''s a peculiar gravity to the place that causes the freaks to congregate here, especially as the sun goes down and the hot smog of the day becomes soft and powdery.

Hollywood Boulevard is the center of that gravity, especially on a Saturday night. Much of the seediness along the thoroughfare has been upgraded in the last 30 years, but there''s still a strip of the old freak show left that''s got nothing on Venice Beach.

> It''s curious that such sorrow and disease would mushroom from a town whose name is synonymous with opulence and beautiful people.

A gang of bikers dressed in leather jackets stake out their turf on the sidewalk in front of a souvenir shop. A cross-dresser with neon lipstick skirts around them, swishing his way past. The bikers glower at the smooth-shaven creature under their thick, grizzled beards. They bark at him, but he merely tosses his faux fur back, blows them a kiss, and takes a haughty puff from his empty cigarette holder. That makes the bikers jeer. Down the street, teens dressed in "scene-wear" sport pink cargoes, yellow and purple hair, and anime eyes. Scene and emo have replaced the old-timey punks here, but these edgy kids are still looking to score a baggie of molly from a dealer who operates from a bus stop shelter. Nearby, under the garish Hard Rock Café sign, a Dianetics dealer entices lost souls to take a free personality test. A male goth wearing a Victorian velvet tailcoat and army boots snorts "rip off" in passing. The Dianetics dealer says pleasantly in reply, "jerk off." The goth shoulders angrily past a ménage à trois of metalheads, vampire-complexioned band groupies wearing dog collars, and black T-shirts flying various jolly rogers. The anorexic woman in the middle is practically carried along by the two men on either side of her. Their long hair is tucked into their skin-tight denims. As a limousine with invisible millionaires or drunk ravers cruises by, one of the metalheads flips it the bird. He drops his middle finger quickly out of respect for the Chevy low rider that follows the limo, packed with gangsters. In the Chevy, mammoth speakers shake the surrounding buildings with gangsta rap, Chicano style. It feels like thunder without the rain.

The stormy, surreal vibe is heightened by movie marquees flashing like heat lightning in the dark: *Thor: Love and Thunder*, *Jurassic World: Dominion*, *Lightyear*. Every blockbuster at the Chinese Theater and El Capitan is a rehash. Nothing new under the moon. "What has been will be again, what has been done will be done again."

It seems to me, as I walk down the sidewalk, that the freaks would be at war with each other if that were permissible. They belong each to their own tribe with their own look and their own rules. A hippie anachronism (maybe a UC professor) in sport coat, tie-dye, and sandals shuffles along like some comic-book version of Moses, but his mere existence elicits expletives from the bikers. And yet somehow, while gangs are killing themselves in earnest, peace prevails on Freak Street.

Maybe it''s because Hollywood is the Land of Make-Believe, and the freaks only come here to play-act. The sidewalk and the street are stages, and all the freaks have their exits and their entrances. Everyone here is playing a bit part in a B movie. It''s a common sight to see the freaks sitting on curbs or gathering at corners, laughing, toking, drinking, dancing.

A street performer in hot pants and a saxophone busker (nailing "Who Can It Be Now?") deepen the effect of street cinema. And yet despair bleeds through the bravado. Some of the faces here look impossibly young. The busker looks to be dying of an opioid addiction. I start to imagine that this is a voyage of the damned, that the denizens of Hollywood are floating out to sea on the Raft of the Medusa. Some of the freaks look only months removed from becoming the walking, talking corpses that lie in dirty heaps on the side streets.

It''s curious that such sorrow and disease would mushroom from a town whose name is synonymous with opulence and beautiful people. The hucksters call it "the glamor capital of the world." Ask anyone who hasn''t been here, and they''ll tell you it''s palm trees and fountains, mansions and convertibles, producers and directors, ingenues and leading men. Nothing could be further from the truth. Somewhere in the distant hills and beaches, the beautiful people do cavort and play. Not in Hollywood. This is the city that the movies birthed and then abandoned. It''s the beggar child of "the Industry." It survives on the alms of cinema''s mystique. It behaves just as you would imagine life imitating art — self-absorbed, hedonistic, amoral art.

It is a moving sight to see tourists standing over the names of favorite performers along the Hollywood Walk of Fame, pointing their cameras like paparazzi straight down at the sidewalk. They have been cheated out of a decent vacation by the hucksters of Hollywood, and still they take pictures with gusto. In the face of terrible disappointment, tourists display heroic good humor. Even though they can''t walk down the sidewalk without dodging puddles left by the night before, they focus on the name in the star. It becomes a game to try to find their favorites among the old greats. Underneath all the filth, the sidewalk stars have the power to bring alive the beauty and excitement of the Hollywood hoped for — the Hollywood of the imagination.

As the sun rises over the tenements and bungalows of Hollywood, the freaks scatter for the shadows. Somehow Hollywood remains the spiritual center of the movie industry. And the moral preachments of Freak Street, fixed in the emulsions of digital celluloid, go forth throughout the world.

*Paul Kortepeter is a writer and educator residing in Indianapolis. This essay was [originally published in The American Spectator](https://spectator.org/hollywood-hellscape/).*', '/images/alley-scene.png', NULL, 'Originally published as "Hollywood Is a Horrifying Hellscape" in The American Spectator, July 23, 2022', 1, 'blog', '2022-07-23T12:00:00.000Z', '2022-07-23T12:00:00.000Z');

INSERT INTO posts (slug, title, excerpt, content, cover_image, cover_focus, source_note, published, section, created_at, updated_at)
VALUES ('writing-rhetoric-faq', 'Writing & Rhetoric: Frequently Asked Questions', 'Common questions about the Writing & Rhetoric series — how it works, where to start, and what makes the progymnasmata different.', '## How is Writing & Rhetoric different than traditional courses in composition?

Writing & Rhetoric employs the classical progymnasmata, the celebrated and intuitive approach to cultivating writing and public speaking skills. Unlike rigid, formulaic essay instruction, the "progym" prioritizes imitation, oral rhetoric, and step-by-step skill development. It weaves together the four modes of discourse — narration, exposition, description, and persuasion — highlighting their interplay in well-crafted compositions. Students begin by retelling, expanding, and analyzing excellent models, growing in confidence as they identify key patterns in foundational writing and experiment with them firsthand. Beyond mechanics, the progym nurtures moral reasoning, with each stage growing in complexity and persuasive depth, guiding young writers toward eloquence and clarity.

## What is the destination of Writing & Rhetoric?

In the end, students will emerge as sharper thinkers and more effective writers, equipped to navigate the "real world" with clarity and persuasion. They will apply their training to journalism, fiction, and nonfiction, as well as fields such as law, business, academia, and public service — wherever strong communication is essential.

The core mission of Writing & Rhetoric, like that of the broader classical education movement, is to cultivate conscientious, principled individuals who contribute meaningfully to society. We aspire to see a growing number of virtuous writers, thinkers, and speakers who elevate culture through wisdom and eloquence.

Specifically, Writing & Rhetoric prepares students for formal rhetoric — the art of persuasive writing and speaking. This includes the five canons of rhetoric (invention, arrangement, style, memory, and delivery), the three branches of oratory (legislative, judicial, and ceremonial), and the three modes of persuasion (ethos, pathos, and logos). Importantly, teachers do not need formal training in rhetoric to effectively guide students through the structured exercises of the progymnasmata, making this approach both accessible and effective.

## What are the progymnasmata?

The progymnasmata are preliminary writing exercises designed to train persuasive writers and speakers. The Greek word shares its root with "gymnasium" — a place of training — emphasizing its role in disciplined practice. Used as a writing manual in the West for centuries, from the Roman Empire through the Middle Ages, Renaissance, and early modern period, the progym systematically develops students'' skills. It progresses from simple narratives to complex compositions and ultimately to persuasive writing.

A student need not begin as a natural writer; the scaffolded structure ensures that weaker writers gain confidence and mastery, while stronger writers are challenged to refine and expand their abilities. The repetitive nature of the exercises allows all students to practice at their own pace, reinforcing key skills. In this method, repetition is not a flaw — it is an essential feature of the learning process.

## What happens at each stage?

The exercises generally ladder through the skills of narration, exposition, analysis, and persuasion, from more concrete to more abstract. However, the elements of persuasion are embedded in every stage.

**Narration** (developing clear, coherent storytelling)
1. Fable — retelling short moral tales with clarity and structure by condensing or expanding them.
2. Narrative I — enhancing stories with description and dialogue.
3. Narrative II — using beginning, middle, and end to guide story structure.

**Exposition** (explaining ideas and concepts clearly)
4. Chreia & Proverb — expanding an anecdote about a wise saying or action with explanation and examples.
5. Refutation & Confirmation — arguing against and in favor of a given narrative.
6. Commonplace — expanding on a virtue or vice with supporting details; the thesis statement is introduced.

**Analysis** (comparing, contrasting, and evaluating people and ideas)
7. Encomium & Vituperation — describing and elaborating on the virtues or vices of a specific person.
8. Comparison — contrasting two people, ideas, or events to highlight similarities and differences, strengths and weaknesses.
9. Description and Impersonation — enhancing descriptive precision and vividness, and adopting the perspective of another person to develop deeper understanding.

**Persuasion** (developing arguments and convincing audiences)
10. Thesis I — constructing formal arguments on abstract topics, e.g. "What is beauty?"
11. Thesis II — constructing speeches in the three branches of rhetoric: legislative, judicial, and ceremonial.
12. Declamation — arguing for or against laws and policies, applying rhetorical skills to real-world issues.

Each category builds upon the previous ones, ensuring a natural progression from storytelling to structured reasoning, then to critical analysis, and finally to persuasive argumentation.

## Are the skills gained through Writing & Rhetoric transferable to other academic situations, such as standardized tests?

Yes. While Writing & Rhetoric follows a different instructional framework than modern composition programs — emphasizing a deeper, more structured development of writing skills — students trained in the progymnasmata are exceptionally well-prepared for high school term papers and college theses.

When preparing for standardized tests, it is always beneficial to practice the specific writing formats required by the test. Along the way, we also recommend that teachers supplement the progymnasmata with letter writing and science/research writing to ensure well-rounded preparation. Book 7: Encomium & Vituperation includes a step-by-step guide to research writing for a strong foundation in academic composition.

## What language skills do students need in order to start Writing & Rhetoric?

By the end of second grade, students should write and identify complete sentences and distinguish between declarative, imperative, and interrogative sentences. They should also expand a single sentence into four or five logically connected sentences, building on the initial idea with detail and coherence. For example:

- Base sentence: "The cat slept."
- Expanded: "The cat slept on the soft rug. It was a sunny morning. She purred quietly. Her tail swished back and forth. What was she dreaming?"

For reading, second graders should independently comprehend texts at a Lexile level of 500L to 650L, depending on individual progress. If students meet these criteria, they are ready to begin Book 1: Fable. Most students begin Fable in third or fourth grade.

## How should I plan my week for language arts instruction?

Each book in the Writing & Rhetoric series makes recommendations for a typical teaching week. Although the elements of grammar are important aspects of the course, its primary focus is composition. We recommend that you teach a simple, but rich, grammar curriculum in parallel with the lessons in Writing and Rhetoric. Three days a week is the recommended minimum for classroom composition.

Reading offers a seamless, enjoyable path for young people to develop strong writing skills. A child''s school routine should include plenty of time for both reading aloud and silent reading.

## Is it possible to complete every exercise and every section in each book?

In a word, no — unless you are only tackling one book a year. Most schools and homeschools will not be able to cover every aspect of the curriculum. Rather, multiple opportunities for practice are built into the Writing & Rhetoric series. If you find that your students have mastered a particular form of writing, you should feel free to skip some lessons. In this case, teachers may choose to present the literature from skipped lessons as part of their history or English lessons. Some teachers may also provide their students with practice in summarizing, critical thinking, and sentence manipulation by doing only the Tell It Back, Talk About It, and Copiousness sections from skipped lessons.

## If I am beginning the W&R program for students in different grade levels, what do you recommend?

Older students, particularly those in fifth grade and beyond, should start at a level where they can write with confidence. For example, if they are already strong storytellers, Chreia & Proverb may be the best entry point. If they have a solid grasp of paragraphing and are ready for essay writing, Commonplace might be a better fit. As mentioned before, repetition is an intentional feature of Writing & Rhetoric, allowing older students to begin at various points without missing essential skills. However, some older students prefer to start at a more foundational level, allowing them to build on their strengths and progress quickly.

## What is the purpose of the Narration (Tell It Back) and Talk About It sections of each lesson?

Narration after reading helps students solidify comprehension when they retell key details in their own words, reinforcing memory and understanding. Discussion with guiding questions sparks critical thinking and encourages students to connect ideas beyond the text. Both sections promote intimacy with the ideas of the main lesson.

## What is the purpose of the Sentence Play and Copiousness sections of each lesson?

These sections provide students with hands-on practice in exploring the versatility of English. By rearranging sentences and devising fresh ways to express the same idea, they discover the language''s dynamism, learning to mold it for clearer communication and stronger persuasion.

## Why isn''t revision included in the earliest books of Writing & Rhetoric?

Revision is generally not appropriate until students have developed a foundational grasp of writing fluency and structure, typically around the fourth or fifth grade. Brain science indicates that revision enhances writing by strengthening memory and self-awareness, but only once the brain''s executive function and metacognition can support the task without overloading young writers.', '/images/writing-rhetoric-series.webp', NULL, NULL, 1, 'faq', '2025-04-01T12:00:00.000Z', '2025-04-01T12:00:00.000Z');

